### ISSUE TITLE
End of play without end of play

### ISSUE THREAD

**Issue by bramtul** [cta-standards/R4WG20-QoE-Metrics#18] opened 2019-04-15 15:03 UTC
An event to register end of playback without the video content being finished (such as when a browser window gets closed mid playback).
Also: ‘Average not started’ - User can excit before video starts and 'Not Started' when starting up is not followed by playing.

**Comment by tonihei** [comment] 2019-04-15 15:05
Duplicate of #12 I think.

**Comment by gheikkila** [comment] 2019-04-30 12:22
I think we earlier discussed this, and concluded that we can never expect that a browser client will send any "end event" if the window is just closed.

**Comment by mlevine84** [comment] 2019-05-08 17:46
WG responded to this issue in comment #12

**Closed as completed by mlevine84** 2019-05-08 17:46 UTC
